#eureka:
#  client:
#    register-with-eureka: false
#  serviceUrl:
#    defaltZone: http://localhost:8000/eureka/
spring:
  profiles:
    active: development
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false




