logging:
  file: ${user.dir}/logs/eureka.log
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
spring:
  profiles:
    active: test
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
eureka.client.serviceUrl.defaltZone: http://106.13.37.124:8000/eureka/

eureka:
  server:
    enable-self-preservation: false  #自我保护，会导致服务不会及时剔除
    eviction-interval-timer-in-ms: 4000 #清理间隔
  instance:
    hostname: 106.13.34.124
