logging:
  file: ${user.dir}/logs/eureka.log
  level:
    org.springframework:
      data: DEBUG
#      security: DEBUG
#spring:
#  security:
#    user:
#      name: linxin
#      password: 123456

#eureka.client.register-with-eureka: false
#eureka.client.fetch-registry: false
eureka:
  server:
    enable-self-preservation: false  #自我保护，会导致服务不会及时剔除
    eviction-interval-timer-in-ms: 4000 #清理间隔
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false

---
server:
  port: 8001
spring:
  profiles: peer1
  application:
    name: eureka_server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8002/eureka/,http://127.0.0.1:8003/eureka/

---
server:
  port: 8002
spring:
  profiles: peer2
  application:
    name: eureka_server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8003/eureka/

---
server:
  port: 8003
spring:
  profiles: peer3
  application:
    name: eureka_server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/
